// <auto-generated />
namespace KhelaGhar.AMS.Model.MigrationAMSDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddAsarNote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAsarNote));
        
        string IMigrationMetadata.Id
        {
            get { return "201410120947547_AddAsarNote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
