#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KhelagharAMSApp.Droid.Resource", IsApplication=true)]

namespace KhelagharAMSApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_smart_meter = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int input_border = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int kg_logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int SplashScreen = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int AsarNameEntry = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int AsarNameLabel = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int AsarNameSearchLabel = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int AsarSearchBtn = 2131099665;
			
			// aapt resource value: 0x7f060008
			public const int LogInButton = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int RelativeLayoutButton = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int TextErrorMessage = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int TextPassword = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int TextUsername = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int img_kg_logo = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int kg_text = 2131099649;
			
			// aapt resource value: 0x7f060012
			public const int listView = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int radio_asar = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int radio_jela = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int radio_search_group = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int radio_upojela = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int relativeLayout1 = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int relativeLayoutPassword = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int relativeLayoutUsername = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LoginLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
